#!/bin/bash

# redhat
if [ -f /etc/redhat-release ]; then
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        os_version="${NAME} ${VERSION}"
    else
        os_version=$(cat /etc/redhat-release)
    fi

    # get number of updates
    sudo dnf -qy makecache || { echo "Error: Unable to update dnf repositories"; exit 1; }
    updates=$(sudo dnf updateinfo list -q | awk -F " " '{print $NF}' | wc -l)

# debian
elif [ -f /etc/debian_version ]; then
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        os_version="${PRETTY_NAME}"
    else
        os_version=$(cat /etc/debian_version)
    fi

    # get number of updates
    sudo apt-get -qq update || { echo "Error: Unable to update apt repositories"; exit 1; }
    updates=$(sudo apt-get -qq -y --ignore-hold --allow-change-held-packages --allow-unauthenticated -s dist-upgrade | grep ^Inst | wc -l)

# unknown os
else
    echo "Error: Not able to determine flavour of Linux."
    exit 1
fi

echo "os_status os_version=\"$os_version\""
echo "os_status updates=$updates"
